"""DISCONNECTED synthetic storage/broker only. Never an Alpaca fallback.

SQLite here stores only values generated by the fixed demonstration. Production
account data requires the PostgreSQL/TDE store. No credential or network imports.
"""
from contextlib import contextmanager
from datetime import datetime, timezone
from decimal import Decimal, Context, localcontext
import json
import os
from pathlib import Path
import sqlite3
import stat
from uuid import UUID

from .intents import Scope, canonical_decimal as dec

SCOPES = (Scope(UUID(int=1), UUID(int=2), UUID(int=3)), Scope(UUID(int=11), UUID(int=12), UUID(int=13)))


def key(scope):
    if scope not in SCOPES:
        raise ValueError('synthetic_scope_required')
    return str(scope.tenant_id) + ':' + str(scope.account_id)


def connect(directory, name, *, create=False):
    directory = Path(directory)
    if not directory.is_absolute() or directory != directory.resolve():
        raise ValueError('unsafe_demo_directory')
    info = directory.lstat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o077:
        raise ValueError('unsafe_demo_directory')
    path = directory / name
    if create:
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_RDWR | os.O_NOFOLLOW, 0o600)
    else:
        fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o077 or info.st_nlink != 1:
            raise ValueError('unsafe_demo_file')
    finally:
        os.close(fd)
    connection = sqlite3.connect(path, isolation_level=None, timeout=5)
    if create:
        connection.execute('PRAGMA application_id=1095321905')
    elif connection.execute('PRAGMA application_id').fetchone() != (1095321905,):
        connection.close()
        raise ValueError('not_synthetic_database')
    connection.execute('PRAGMA trusted_schema=OFF')
    connection.execute('PRAGMA synchronous=FULL')
    connection.execute('PRAGMA journal_mode=DELETE')
    connection.execute('PRAGMA foreign_keys=ON')
    return connection


def initialize(directory):
    directory = Path(directory)
    directory.mkdir(mode=0o700, parents=False, exist_ok=False)
    SyntheticStore(directory, create=True).close()
    SyntheticBroker(directory, create=True).close()


class SyntheticStore:
    def __init__(self, directory, *, create=False):
        self.db = connect(directory, 'synthetic-ledger.sqlite', create=create)
        if not create:
            return
        self.db.execute('CREATE TABLE IF NOT EXISTS state (scope TEXT PRIMARY KEY, revision INTEGER NOT NULL, body TEXT NOT NULL)')
        self.db.execute('CREATE TABLE IF NOT EXISTS event (scope TEXT NOT NULL, revision INTEGER NOT NULL, kind TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY(scope,revision))')
        self.db.execute("CREATE TRIGGER IF NOT EXISTS event_immutable_update BEFORE UPDATE ON event BEGIN SELECT RAISE(ABORT,'immutable'); END")
        self.db.execute("CREATE TRIGGER IF NOT EXISTS event_immutable_delete BEFORE DELETE ON event BEGIN SELECT RAISE(ABORT,'immutable'); END")
        from .workflow import initial_state
        for scope in SCOPES:
            self.db.execute('INSERT OR IGNORE INTO state VALUES (?,0,?)', (key(scope), json.dumps(initial_state())))

    def read(self, scope):
        return json.loads(self.db.execute('SELECT body FROM state WHERE scope=?', (key(scope),)).fetchone()[0])

    @contextmanager
    def transaction(self, scope, event):
        identity = key(scope)
        self.db.execute('BEGIN IMMEDIATE')
        try:
            revision, body = self.db.execute('SELECT revision,body FROM state WHERE scope=?', (identity,)).fetchone()
            state = json.loads(body)
            yield state
            result = json.dumps(state, sort_keys=True, separators=(',', ':'), allow_nan=False)
            if len(result) > 524288:
                raise ValueError('demo_capacity')
            if result != body:
                self.db.execute('UPDATE state SET revision=?,body=? WHERE scope=? AND revision=?', (revision+1,result,identity,revision))
                self.db.execute('INSERT INTO event VALUES (?,?,?,?)', (identity,revision+1,event,result))
            self.db.execute('COMMIT')
        except BaseException:
            self.db.execute('ROLLBACK')
            raise

    def events(self, scope):
        return self.db.execute('SELECT revision,kind FROM event WHERE scope=? ORDER BY revision', (key(scope),)).fetchall()

    def close(self):
        self.db.close()


class SyntheticBroker:
    security_id = UUID(int=5)

    def __init__(self, directory, *, create=False):
        self.db = connect(directory, 'synthetic-broker.sqlite', create=create)
        self.partial = False
        self.timeout = False
        if not create:
            return
        self.db.execute('CREATE TABLE IF NOT EXISTS account (scope TEXT PRIMARY KEY, body TEXT NOT NULL)')
        for scope in SCOPES:
            self.db.execute('INSERT OR IGNORE INTO account VALUES (?,?)', (key(scope),
                json.dumps({'cash': '200', 'position': '0', 'orders': {}, 'fills': {}, 'submissions': 0})))
        self.partial = False
        self.timeout = False

    def market(self):
        return {'bid': Decimal('20'), 'ask': Decimal('20.01'), 'open': True,
                'time': datetime.now(timezone.utc)}

    def snapshot(self, scope):
        return json.loads(self.db.execute('SELECT body FROM account WHERE scope=?', (key(scope),)).fetchone()[0])

    @contextmanager
    def _change(self, scope):
        self.db.execute('BEGIN IMMEDIATE')
        try:
            state = self.snapshot(scope)
            yield state
            self.db.execute('UPDATE account SET body=? WHERE scope=?', (json.dumps(state),key(scope)))
            self.db.execute('COMMIT')
        except BaseException:
            self.db.execute('ROLLBACK')
            raise

    def _fill(self, state, client, fraction):
        order = state['orders'][client]
        target = Decimal(order['quantity']) * fraction
        delta = target - Decimal(order['filled_quantity'])
        if delta <= 0:
            return
        cost = delta * Decimal(order['limit_price'])
        identifier = client + ':' + dec(target)
        state['fills'][identifier] = {'client_id': client, 'quantity': dec(delta), 'value': dec(cost)}
        order['filled_quantity'] = dec(target)
        order['filled_value'] = dec(Decimal(order['filled_value']) + cost)
        order['status'] = 'FILLED' if target == Decimal(order['quantity']) else 'PARTIAL'
        state['cash'] = dec(Decimal(state['cash']) - cost)
        state['position'] = dec(Decimal(state['position']) + delta)

    def submit(self, scope, order):
        with localcontext(Context(prec=60)):
            with self._change(scope) as state:
                client = order['client_id']
                if client in state['orders']:
                    if state['orders'][client]['digest'] != order['digest']:
                        raise ValueError('duplicate_conflict')
                    return
                state['orders'][client] = {n: order[n] for n in ('client_id','digest','quantity','limit_price','filled_quantity','filled_value')}
                state['orders'][client]['status'] = 'ACCEPTED'
                state['submissions'] += 1
                self._fill(state, client, Decimal('0.5') if self.partial else Decimal('1'))
        if self.timeout:
            raise TimeoutError('synthetic_ambiguous_response')

    def complete(self, scope, client):
        with localcontext(Context(prec=60)):
            with self._change(scope) as state:
                self._fill(state, client, Decimal('1'))

    def close(self):
        self.db.close()
