'use strict';
const byId=id=>document.getElementById(id);
const say=text=>{byId('notice').textContent=text;};
function field(parent,name,value){const label=document.createElement('dt');label.textContent=name;const item=document.createElement('dd');item.textContent=String(value);parent.append(label,item);}
async function request(path,body){const cancel=new AbortController();const timer=setTimeout(()=>cancel.abort(),95000);try{const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store',credentials:'omit',redirect:'error',signal:cancel.signal});if(!response.ok)throw Error();return await response.json();}finally{clearTimeout(timer);}}
async function status(){const data=await request('/api/status');const area=byId('status');area.replaceChildren();for(const [name,key] of [['Application','application'],['Access','transport'],['PostgreSQL','database'],['Local inference','local_model'],['Model','model'],['Alpaca PAPER','account_data'],['Observed','observed_at']])field(area,name,data[key]);}
byId('refresh').onclick=()=>status().then(()=>say('System status refreshed.')).catch(()=>say('Status unavailable. Check the local service.'));
byId('research').onclick=async()=>{const button=byId('research');button.disabled=true;byId('result').replaceChildren();say('Local research running. No brokerage action is possible.');try{const data=await request('/api/research',{symbol:byId('symbol').value});const result=byId('result');const dl=document.createElement('dl');field(dl,'Security',data.symbol);field(dl,'Action',data.action);field(dl,'Bull-case question',data.questions.bull_question);field(dl,'Bear-case question',data.questions.bear_question);field(dl,'Evidence needed',data.questions.evidence_needed);field(dl,'Evidence status',data.evidence_status);field(dl,'Confidence',data.confidence);field(dl,'Risk gate',data.risk_result);field(dl,'Reasons',data.risk_reasons.join(', '));field(dl,'Model / prompt',data.model+' / '+data.prompt_version);field(dl,'Generated',data.generated_at);result.append(dl);say('Research checklist complete. Unverified, not an executable recommendation.');}catch{say('Research unavailable, busy or refused. Wait 15 seconds and retry; no order was created.');}finally{button.disabled=false;}};
status().then(()=>say('LAN workspace ready. Credential entry and trading are disabled.')).catch(()=>say('Status unavailable.'));
