'use strict';
const byId=id=>document.getElementById(id);
const views={dashboard:['YOUR RESEARCH WORKSPACE','Dashboard','A clear view of your research, connections and next steps.'],research:['EVIDENCE BEFORE CONVICTION','Research','Investigate a security. Challenge the thesis. Identify what is missing.'],opportunities:['DISCOVERY & EXPLANATION','Opportunities','Understand why a candidate is interesting before deciding what to do.'],portfolio:['PAPER ACCOUNT','Portfolio','Holdings, exposure and performance grounded in actual account data.'],orders:['CONTROLLED EXECUTION','Orders','Every order needs a proposal, a risk decision and human approval.'],strategies:['HYPOTHESES & MEASUREMENT','Signal lab','Find out what works, after costs and outside the original sample.'],activity:['WORKSPACE HISTORY','Activity','Your research and system checks in this browser session.'],system:['CONNECTIONS & OPERATIONS','System','Service health, account access and the current safety boundary.']};
const companies={SPY:'SPDR S&P 500 ETF',AAPL:'Apple',MSFT:'Microsoft',NVDA:'NVIDIA'};
const say=(text,error=false)=>{byId('notice').textContent=text;byId('notice').classList.toggle('error',error);};
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
function field(parent,name,value){parent.append(element('dt',name),element('dd',String(value??'Unavailable')));}
function dateLabel(value){const date=new Date(value);return Number.isNaN(date.getTime())?'Timestamp unavailable':date.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function activity(message){const row=element('li');const time=element('time',dateLabel(Date.now()));time.dateTime=new Date().toISOString();row.append(element('span',message),time);byId('activity-list').prepend(row);while(byId('activity-list').children.length>20)byId('activity-list').lastChild.remove();byId('activity-empty').hidden=true;}
function navigate(){const name=location.hash.slice(1);const view=Object.hasOwn(views,name)?name:'dashboard';for(const key of Object.keys(views))byId('view-'+key).hidden=key!==view;for(const link of document.querySelectorAll('#navigation a')){if(link.dataset.view===view)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');}const [eyebrow,title,description]=views[view];byId('page-eyebrow').textContent=eyebrow;byId('page-title').textContent=title;byId('breadcrumb').textContent=title;byId('page-description').textContent=description;document.title='ai-invest · '+title;}
window.addEventListener('hashchange',navigate);navigate();
async function request(path,body){const cancel=new AbortController();const timer=setTimeout(()=>cancel.abort(),95000);try{const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store',credentials:'omit',redirect:'error',signal:cancel.signal});if(!response.ok)throw Error('request_refused');return await response.json();}finally{clearTimeout(timer);}}
function healthRow(name,label,kind){const row=element('div',undefined,'health-row');row.append(element('span',name),element('span',label,'health-state '+kind));return row;}
async function status(){const data=await request('/api/status');const databaseReady=data.database==='READY_WAL_ENCRYPTION_ON';const modelReady=data.local_model==='READY';const running=data.application==='RUNNING';const area=byId('status');area.replaceChildren();for(const [name,value] of [['Application',running?'Running':data.application],['Transport','HTTP · public to LAN; no private account session'],['PostgreSQL',databaseReady?'Ready · WAL encryption enabled':data.database],['Local inference',modelReady?'Ready':data.local_model],['Local model',data.model],['Alpaca PAPER',data.account_data==='NOT_CONNECTED'?'Not connected':data.account_data],['Trading','Disabled'],['Observed',dateLabel(data.observed_at)]])field(area,name,value);byId('health-summary').replaceChildren(healthRow('Application',running?'Running':'Unavailable',running?'ready':'attention'),healthRow('Encrypted PostgreSQL',databaseReady?'Ready':'Unavailable',databaseReady?'ready':'attention'),healthRow('Local inference',modelReady?'Ready':'Unavailable',modelReady?'ready':'attention'),healthRow('Alpaca PAPER','Not connected',''));byId('status-freshness').textContent='Observed '+dateLabel(data.observed_at)+' · refresh for a new observation';byId('model-summary').textContent=modelReady?'Ready':'Unavailable';byId('model-summary-note').textContent=modelReady?'Local research questions · unverified':'Local service needs attention';byId('health-dot').className=running&&databaseReady&&modelReady?'ready':'attention';byId('health-label').textContent=running&&databaseReady&&modelReady?'Local services ready':'Service needs attention';return data;}
async function refresh(){const button=byId('refresh');button.disabled=true;try{await status();say('Status refreshed. Account connection and trading remain unavailable.');activity('System status refreshed');}catch{say('Cannot refresh system status. Previously displayed observations may be stale.',true);byId('health-dot').className='attention';byId('health-label').textContent='Status unavailable';activity('System status check unavailable');}finally{button.disabled=false;}}
byId('refresh').addEventListener('click',refresh);
for(const button of document.querySelectorAll('[data-symbol]'))button.addEventListener('click',()=>{byId('symbol').value=button.dataset.symbol;location.hash='research';byId('symbol').focus();});
function questionCard(title,text,kind){const card=element('section',undefined,'question-card '+kind);card.append(element('span','MODEL QUESTION · UNVERIFIED','mini-label'),element('h3',title),element('p',text));return card;}
function renderResearch(data){const result=byId('result');result.replaceChildren();const heading=element('div',undefined,'research-result-heading');const identity=element('div',undefined,'security-title');const identityText=element('div');identityText.append(element('h2',data.symbol+' · Research plan'),element('p',(companies[data.symbol]||'Public security')+' · '+dateLabel(data.generated_at)));identity.append(element('span',data.symbol,'ticker-icon'),identityText);heading.append(identity,element('span','WATCH ONLY · UNVALIDATED','pill warning-pill'));const grid=element('div',undefined,'result-grid');grid.append(questionCard('The bullish case',data.questions.bull_question,''),questionCard('The strongest counterargument',data.questions.bear_question,'contrary'),questionCard('Evidence needed before a conclusion',data.questions.evidence_needed,'evidence'));const footnotes=element('div',undefined,'research-footnotes');const provenance=element('section',undefined,'panel');provenance.append(element('h2','Provenance & confidence'));const dl=element('dl',undefined,'detail-list');field(dl,'Classification','Model questions, not verified facts or a quantitative signal');field(dl,'Evidence','No current market or company sources collected');field(dl,'Confidence','Uncalibrated · insufficient evidence');field(dl,'Local model',data.model);field(dl,'Prompt version',data.prompt_version);field(dl,'Generated',dateLabel(data.generated_at));provenance.append(dl);const risk=element('section',undefined,'panel');risk.append(element('span','NO EXECUTION AUTHORITY','mini-label'),element('h2','Research is not an order'),element('p','The model has not produced an approved trade proposal. Deterministic financial controls remain outside model authority.','subtle'));const reasons={NO_AUTHENTICATED_APPROVAL:'No authenticated human approval',NO_CONNECTED_ACCOUNT:'No connected PAPER account',NO_FRESH_MARKET_EVIDENCE:'No fresh market evidence'};const list=element('ul',undefined,'reason-list');for(const reason of data.risk_reasons||[])list.append(element('li',reasons[reason]||'Required control unavailable'));risk.append(list);const blocked=element('button','PAPER approval unavailable','button secondary');blocked.type='button';blocked.disabled=true;risk.append(blocked);footnotes.append(provenance,risk);result.append(heading,grid,footnotes);}
byId('research').addEventListener('click',async()=>{const button=byId('research');const select=byId('symbol');const symbol=select.value;button.disabled=true;select.disabled=true;byId('research-progress').hidden=false;byId('research-empty').hidden=true;byId('result').replaceChildren();say('Researching '+symbol+' locally. This generates questions, not an executable recommendation.');try{const data=await request('/api/research',{symbol});renderResearch(data);say('Research plan complete. Verify each question against current primary evidence.');activity(symbol+' · Local research plan generated, unverified');}catch{say('Research is busy, unavailable or refused. Wait 15 seconds and retry. No order was created.',true);byId('research-empty').hidden=false;activity(symbol+' · Research request unavailable');}finally{byId('research-progress').hidden=true;button.disabled=false;select.disabled=false;}});
status().then(()=>{say('Workspace ready. Start with a research question; no brokerage action is enabled.');activity('Workspace opened · service status observed');}).catch(()=>{say('System status unavailable. Refresh to retry.',true);byId('health-dot').className='attention';byId('health-label').textContent='Status unavailable';});
